[package]
name = "photiso_rust"
version = "0.1.0"
authors = ["Geoff Cox <geoff.cox@live.com>"]
edition = "2018"

[dependencies]
toml = "0.5.7"
serde = { version = "1.0", features = ["derive"] }
kamadak-exif = "0.5.2"