[directories]
unorganized = ".\\test_files\\unorganized"
organized = ".\\test_files\\organized"
duplicates = ".\\test_files\\duplicates"

[options]
#output = "none" | "normal" | "verbose"
output = "normal"