[directories]
unorganized = ".\\test_files\\organized"
organized = ".\\test_files\\organized"
duplicates = ".\\test_files\\duplicates"

[options]
#output = "none" | "compact" | "default"
output = "compact"
stopOnError = true